export const boardsArray = [
  {
    id: '1',
    title: 'First board',
    favorite: true,
    columns: ['1', '2', '3'],
  },
  {
    id: '2',
    title: 'Second board',
    favorite: false,
    columns: ['4', '5', '6'],
  },
  {
    id: '3',
    title: 'Trid board',
    favorite: true,
    columns: ['7', '9', '10'],
  },
  {
    id: '4',
    title: 'Fourth board',
    favorite: false,
    columns: ['11', '12', '13'],
  },
  {
    id: '5',
    title: 'Fifth board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '6',
    title: '6 board ',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '7',
    title: '7 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '8',
    title: '8 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '9',
    title: '9 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '10',
    title: '10 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '11',
    title: '11 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '12',
    title: '12 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '13',
    title: '13 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '14',
    title: '14 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '15',
    title: '15 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '16',
    title: '16 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
  {
    id: '17',
    title: '17 board',
    favorite: false,
    columns: ['14', '15', '16'],
  },
].reverse()
